spring:
  eureka:
    client:
      service-url:
        defaultZone: https://backend-eureka-production.up.railway.app/eureka
    instance:
      prefer-ip-address: true
logging:
  level:
    org.elasticsearch.client.RestClient: TRACE
