server:
  port: 8082

spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:mysql://localhost:3306/dbpeliculas
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 

eureka:
  client:
    service-url:
      defaultZone: https://backend-eureka-production.up.railway.app/eureka/
